Complete: Testing Practice -Odin Project
imahnama/testing-practice pull request #1
Opened 2020-08-25 12:32 UTC by imahnama

## In this Project we:
- Install Jest
- Create function Capitalize, reverseString, calculator, caesarCipher and arrayAnalysis.
- Write tests for the above-mentioned functions
- Add ReadMe file
-Add linters for the project

2020-08-25 18:30 UTC, mosaaleb requested changes
#### Well done @imahnama @OdongAlican :clap:

Most requirements are handled, yet there is bug in CaesarCipher function. Check out my comment below.

- **[SUGGESTION]** Let's better organize your modules and tests and put them all inside `src` folder, with a sub folders for both your modules and another for tests.



Please fix the below requirement and submit a new code review.


##### Muhammad Ebeid

2020-08-25 18:30 UTC, mosaaleb commented on caesarCipher.test.js
> +import caesarCipher from './caesarCipher';
- [ ] When I test the string "If he had anything confidential to say" against your caesarCipher function:

I got a failing test:

```js
// ohk > oHk
Expected: "Pm ol ohk hufaopun jvumpkluaphs av zhf"
Received: "Pm ol oHk hufaopun jvumpkluaphs av zhf"
```

2020-08-25 19:30 UTC, imahnama commented
> #### Well done @imahnama @OdongAlican 👏
> Most requirements are handled, yet there is a bug in CaesarCipher function. Check out my comment below.
> 
> * **[SUGGESTION]** Let's better organize your modules and tests and put them all inside the `src` folder, with subfolders for both your modules and another one for tests.
> * [ ]  There are some missing test-cases in CaesarCipher:
>   
>   * It has a test for wrapping from `z` to `a`.
>   * It has a test for keeping the same case.
> 
> Please fix the below requirement and submit a new code review.
> 
> ##### Muhammad Ebeid

@mosaaleb Thank you for your suggestion. We rechecked the test with your input and its passing. Kindly re-check from your end.
![testing](https://user-images.githubusercontent.com/25789009/91218947-8ab14880-e722-11ea-9824-34f98dc09d20.png)

2020-08-25 21:26 UTC, mosaaleb commented
Hi @imahnama Thanks for reaching out.

This is caused by a bug in your caesarCipher function, If you tried to change the order of these two test-cases, or write another test-case outside, it will fail:
![Screenshot from 2020-08-25 22-18-48](https://user-images.githubusercontent.com/4246637/91223702-538e6780-e721-11ea-9491-8ab50e5c2a5d.png)

Both of them are failing.

The issue is that  `capsLetter` array doesn't get reset between function calls, It will have the same value from the past function call despite your are initializing it with `const capsLetters = [];`. This behavior happens because of  [closures](https://javascript.info/closure). Please make sure to read about it.

To solve the issue, you can reset `capsLetters` manually between function calls.

Feel free to contact me on Slack if you have further questions.

2020-08-26 00:09 UTC, OdongAlican commented
hey @mosaaleb. Thanks a lot for the Feedback. We have implemented the requested changes. Could you please review the project and give us feedback.

2020-08-26 02:10 UTC, Ispirett approved these changes
## Status Approved :+1: 
Really good job @folks you did great work with all your changes made. :+1:

2020-08-26 09:29 UTC, merged